Introduce xmlstarlet, Unity 2.3, Bug fixes/typos
Signed-off-by: JohnFawkes <33303104+JohnFawkes@users.noreply.github.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -17,14 +17,15 @@ rm -rf $TMPDIR 2>/dev/null
 mkdir -p $INSTALLER
 
 # Extract Unityfiles
-unzip -o "$ZIP" 'common/unityfiles.tar.gz' -d $INSTALLER >&2
-[ -f "$INSTALLER/common/unityfiles.tar.gz" ] || { echo "! Unable to extract zip file !"; exit 1; }
+unzip -o "$ZIP" 'common/unityfiles/tools.tar.gz' 'common/unityfiles/util_functions.sh' -d $INSTALLER >&2
+[ -f "$INSTALLER/common/unityfiles/tools.tar.gz" ] || { echo "! Unable to extract zip file !"; exit 1; }
 
 # Load Util_Functions, Add In-House Binaries to PATH, Start Bash Shell
-ARCH32=`getprop ro.product.cpu.abi | cut -c-3`
-[ -z $ARCH32 ] && ARCH32=`getprop ro.product.cpu.abi2 | cut -c-3`
-[ -z $ARCH32 ] && ARCH32=arm
-(tar -xf $INSTALLER/common/unityfiles.tar.gz -C $INSTALLER/common) || { echo "! Unable to extract unity files !"; exit 1; }
-chmod -R 755 $INSTALLER/common/unityfiles/$ARCH32
-echo $PATH | grep -q "$INSTALLER/common/unityfiles/$ARCH32" || export PATH=$INSTALLER/common/unityfiles/$ARCH32:$PATH
+export ARCH32=`getprop ro.product.cpu.abi | cut -c-3`
+[ -z $ARCH32 ] && export ARCH32=`getprop ro.product.cpu.abi2 | cut -c-3`
+[ -z $ARCH32 ] && export ARCH32=arm
+(tar -xf $INSTALLER/common/unityfiles/tools.tar.gz -C $INSTALLER/common/unityfiles) || { echo "! Unable to extract unity tools !"; exit 1; }
+cp -f $INSTALLER/common/unityfiles/tools/$ARCH32/magiskinit $INSTALLER/common/unityfiles/tools/$ARCH32/magiskpolicy
+chmod -R 755 $INSTALLER/common/unityfiles/tools/$ARCH32
+echo $PATH | grep -q "$INSTALLER/common/unityfiles/tools/$ARCH32" || export PATH=$INSTALLER/common/unityfiles/tools/$ARCH32:$PATH
 bash $INSTALLER/common/unityfiles/util_functions.sh
